dist: trusty
sudo: require
language: cpp
compiler: g++
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
            - gcc-6
            - cmake
before_install: sudo apt-get update -qq
install: export CXX="g++-6"
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./unittest
