dist: trusty
sudo: require
language: cpp
compiler: gcc
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
            - gcc-6
            - cmake
        script:
            - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
            - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./unittest
